CREATE TABLE EMPRESA(
	id bigint generated by default as identity,
	nome varchar(100) unique not null,
	primary key (id)
);

CREATE TABLE OPERACOES(
	id bigint generated by default as identity,
	periodo int not null,
	qtd_notas int not null,
	qtd_debitos int not null,
	id_empresa bigint not null,
	primary key (id)
);

CREATE TABLE NOTAS(
	id bigint generated by default as identity,
	periodo int not null,
	numero_nota int not null,
	tp_nota varchar(20) not null,
	id_empresa bigint not null,
	primary key (id)
);

ALTER TABLE NOTAS ADD CONSTRAINT FK1 FOREIGN KEY (id_empresa) REFERENCES EMPRESA;
ALTER TABLE OPERACOES ADD CONSTRAINT FK2 FOREIGN KEY (id_empresa) REFERENCES EMPRESA;

INSERT INTO EMPRESA (nome) VALUES ('Empresa 1');
INSERT INTO EMPRESA (nome) VALUES ('Empresa 2');
INSERT INTO EMPRESA (nome) VALUES ('Empresa 3');
INSERT INTO EMPRESA (nome) VALUES ('Empresa 4');
INSERT INTO EMPRESA (nome) VALUES ('Empresa 5');

INSERT INTO OPERACOES(periodo, qtd_notas, qtd_debitos, id_empresa) VALUES(202001, 20, 10, 1);
INSERT INTO OPERACOES(periodo, qtd_notas, qtd_debitos, id_empresa) VALUES(202001, 25, 12, 2);
INSERT INTO OPERACOES(periodo, qtd_notas, qtd_debitos, id_empresa) VALUES(202001, 29, 20, 3);
INSERT INTO OPERACOES(periodo, qtd_notas, qtd_debitos, id_empresa) VALUES(202001, 50, 35, 4);
INSERT INTO OPERACOES(periodo, qtd_notas, qtd_debitos, id_empresa) VALUES(202001, 100, 70, 5);

INSERT INTO NOTAS(periodo, numero_nota, tp_nota, id_empresa) VALUES(202001, 123, 'FISCAL', 1);
INSERT INTO NOTAS(periodo, numero_nota, tp_nota, id_empresa) VALUES(202001, 456, 'FISCAL', 1);
INSERT INTO NOTAS(periodo, numero_nota, tp_nota, id_empresa) VALUES(202001, 789, 'FISCAL', 1);
INSERT INTO NOTAS(periodo, numero_nota, tp_nota, id_empresa) VALUES(202001, 621, 'DEBITO', 1);
INSERT INTO NOTAS(periodo, numero_nota, tp_nota, id_empresa) VALUES(202001, 634, 'DEBITO', 1);
INSERT INTO NOTAS(periodo, numero_nota, tp_nota, id_empresa) VALUES(202001, 665, 'DEBITO', 1);
INSERT INTO NOTAS(periodo, numero_nota, tp_nota, id_empresa) VALUES(202001, 999, 'FISCAL', 2);
INSERT INTO NOTAS(periodo, numero_nota, tp_nota, id_empresa) VALUES(202001, 888, 'FISCAL', 2);
INSERT INTO NOTAS(periodo, numero_nota, tp_nota, id_empresa) VALUES(202001, 777, 'DEBITO', 2);

